rpisite/rpiapp/urls.py
from django.urls import path
from .views import delete_views, detail_views, edit_views, misc_views, search_views, user_views

app_name = "rpiapp"
urlpatterns = [

    # User URLs
    path("register/", user_views.register_user, name="register_user"),
    path("login/", user_views.login_user, name="login_user"),
    path("logout/", user_views.logout_user, name="logout_user"),
    path("users/<int:user_id>/", user_views.user_profile, name="user_profile"),
    path("users/<int:user_id>/edit/", user_views.edit_profile, name="edit_profile"),
    path("users/<int:user_id>/delete", user_views.delete_profile, name="delete_profile"),

    # Search URLs
    path("users/search/", search_views.user_search, name="user_search"),
    path("leagues/search/", search_views.league_search, name="league_search"),
    path("leagues/<int:league_id>/teams/search/", search_views.team_search, name="team_search"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/search/", search_views.game_search, name="game_search"),
    
    # Index URL
    path("", detail_views.index, name="index"),

    # Detail URLs
    path("leagues/<int:league_id>/", detail_views.league_details, name="league_details"),
    path("leagues/<int:league_id>/teams/<int:team_id>/", detail_views.team_details, name="team_details"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/", detail_views.season_details, name="season_details"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/", detail_views.game_details, name="game_details"),

    # Edit URLs
    path("leagues/<int:league_id>/edit/", edit_views.edit_league, name="edit_league"),
    path("leagues/<int:league_id>/teams/<int:team_id>/edit/", edit_views.edit_team, name="edit_team"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/edit/", edit_views.edit_season, name="edit_season"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/edit/", edit_views.edit_game, name="edit_game"),

    # Delete URLs
    path("leagues/<int:league_id>/delete/", delete_views.delete_league, name="delete_league"),
    path("leagues/<int:league_id>/teams/<int:team_id>/delete/", delete_views.delete_team, name="delete_team"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/delete/", delete_views.delete_season, name="delete_season"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/delete/", delete_views.delete_game, name="delete_game"),

    # Add Games through File
    path("leagues/<int:league_id>/seasons/<int:season_id>/addgames/", misc_views.bulk_game_upload, name="bulk_game_upload")
]

rpisite/rpisite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [

    path("", RedirectView.as_view(url='/rpiapp/')),
    path('admin/', admin.site.urls),
    path('rpiapp/', include('rpiapp.urls'))

]

rpisite/rpiapp/forms/edit_forms.py
from django import forms
from ..models import League, Team, Season, Game

class EditLeagueForm(forms.ModelForm):
    class Meta:
        model = League
        exclude = ('created_by',)

class EditTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ('created_by', 'league',)

class EditSeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        exclude = ('created_by', 'league',)

class EditGameForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = ('date','winner','loser','home_team','away_team')
    
    def __init__(self, *args, **kwargs):
        instance = kwargs['instance']
        super(EditGameForm, self).__init__(*args, **kwargs)
        self.fields['date'] = forms.DateField(widget=forms.widgets.SelectDateWidget(years=range(instance.season.start_date.year, instance.season.end_date.year+1)))
        self.fields['winner'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['loser'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['home_team'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['away_team'].queryset = instance.season.league.teams.all().order_by("name")

rpisite/rpiapp/forms/user_forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email')

rpisite/rpiapp/views/bulk_upload_view.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..models import Team, Season, Game
from ..utils.bulk_rpi import bulk_create_games
import csv
import datetime

@login_required
def bulk_game_upload(request, league_id, season_id):

    season = get_object_or_404(Season, id=season_id)
    league = season.league

    if request.method == 'POST':
        games_csv = request.FILES.get('games_csv')
        decoded_games_csv = games_csv.read().decode('utf-8').splitlines()
        games_csv_reader = csv.reader(decoded_games_csv, delimiter=",")
        next(games_csv_reader)
        games = []
        for row in games_csv_reader:
            date = datetime.datetime.strptime(row[0], '%m/%d/%Y').date()
            if date < season.start_date or date > season.end_date:
                messages.error(request, f"Contains game outside of date range ({season.start_date})-({season.end_date})")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            home_team, ht_created = Team.objects.get_or_create(name=row[3], league=league, created_by=request.user)
            away_team, at_created = Team.objects.get_or_create(name=row[4], league=league, created_by=request.user)
            winner, w_created = Team.objects.get_or_create(name=row[1], league=league, created_by=request.user)
            loser, l_created = Team.objects.get_or_create(name=row[2], league=league, created_by=request.user)
            created_by = request.user
            game = Game(
                created_by = created_by,
                date = date,
                home_team = home_team,
                away_team=away_team,
                winner=winner,
                loser=loser,
                season=season,
                league=league,
                bulk_processing=True
            )
            games.append(game)
            if w_created:
                messages.success(request, f"Team '{winner}' created")
            if l_created:
                messages.success(request, f"Team '{loser}' created")
            if ht_created:
                messages.success(request, f"Team '{home_team}' created")
            if at_created:
                messages.success(request, f"Team '{away_team}' created")
        bulk_create_games(season, games, True)
        messages.success(request, "Games imported successfully")
        return HttpResponseRedirect(reverse('rpiapp:season_details', kwargs={"league_id":league.id,
                                                                             "season_id":season.id}))
    
    context = {
        "season" : season
    }
    return render(request, "rpiapp/add_games_bulk.html", context)

rpisite/rpiapp/views/delete_views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..models import League, Team, Season, Game
from ..utils.bulk_rpi import bulk_calculate_rpis, toggle_bulk_processing

@login_required
def delete_league(request, league_id):
    
    if request.method == 'POST':
        league = get_object_or_404(League, id=league_id)
        if request.user == league.created_by or request.user.is_superuser:
            league.delete()
            messages.success(request, f"League '{league}' deleted successfully")
        else:
            messages.error(request, "You cannot delete this league as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_team(request, league_id, team_id):

    if request.method == 'POST':
        league = get_object_or_404(League, id=league_id)
        team = get_object_or_404(Team, id=team_id)
        if request.user == team.created_by or request.user.is_superuser:
            league_games = league.league_games.all()
            league_seasons = league.seasons.all()
            toggle_bulk_processing(league_games, True)            
            team.delete()
            for season in league_seasons:
                bulk_calculate_rpis(season, season.season_games.all())
            toggle_bulk_processing(league_games, False) 
            messages.success(request, f"Team '{team}' deleted successfully")
        else:
            messages.error(request, "You cannot delete this team as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_season(request, league_id, season_id):

    if request.method == 'POST':
        season = get_object_or_404(Season, id=season_id)
        if request.user == season.created_by or request.user.is_superuser:
            season.delete()
            messages.success(request, f"Season deleted successfully: {season.name}")
        else:
            messages.error(request, "You cannot delete this season as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_game(request, league_id, season_id, game_id):

    if request.method == 'POST':
        game = get_object_or_404(Game, id=game_id)

        if request.user == game.created_by or request.user.is_superuser:
            game.delete()
            messages.success(request, f"Game between {game.home_team} and {game.away_team} on {game.date} deleted successfully")
        else:
            messages.error(request, "You cannot delete this game as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

rpisite/rpiapp/views/detail_views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from ..forms.add_forms import AddLeagueForm, AddTeamForm, AddSeasonForm, AddGameForm
from ..models import League, Team, Season, Game, RPI
from django.contrib.auth.models import User
from ..utils.rpi import get_season_params

def index(request):

    # Show the most recent 5 games
    latest_games = Game.objects.all().order_by("-date")[:5]

    superuser = User.objects.filter(is_superuser=True)[0]

    pro_leagues_list = ["National Football League", "National Basketball Association", "Major League Baseball", "National Hockey League"]
    pro_leagues = League.objects.filter(name__in=pro_leagues_list, created_by=superuser).order_by("name")

    college_leagues_list = ["NCAA Men's Hockey","NCAA Women's Hockey","NCAA Men's Basketball","NCAA Women's Basketball","NCAA Baseball","NCAA Football",]
    college_leagues = League.objects.filter(name__in=college_leagues_list, created_by=superuser)

    if request.method == 'POST':
        add_league_form = AddLeagueForm(request.POST)
        if add_league_form.is_valid():
            league = add_league_form.save()
            league.created_by = request.user
            league.save()
            messages.success(request, f"League '{league}' created successfully")
            return HttpResponseRedirect(reverse("rpiapp:league_details", args=[league.id]))
    else:
        add_league_form = AddLeagueForm()

    context = {
        "add_league_form" : add_league_form,
        "latest_games" : latest_games,
        "pro_leagues" : pro_leagues,
        "college_leagues" : college_leagues
    }

    return render(request, "rpiapp/detail_templates/index.html", context)

def league_details(request, league_id):

    league = get_object_or_404(League, id=league_id)
    league_seasons = league.seasons.all().order_by("-start_date")
    league_teams = league.teams.all().order_by("name")
    add_team_form = AddTeamForm()
    add_season_form = AddSeasonForm()

    if request.method == 'POST':
        if 'add_team' in request.POST:
            add_team_form = AddTeamForm(request.POST)
            if add_team_form.is_valid():
                if Team.objects.filter(league=league, name=add_team_form.cleaned_data['name']).exists():
                    messages.error(request, "Team with this name in this league exists already")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                team = add_team_form.save()
                team.league = league
                team.created_by = request.user
                team.save()
                messages.success(request, f"Team {team} created successfully")
        if 'add_season' in request.POST:
            add_season_form = AddSeasonForm(request.POST)
            if add_season_form.is_valid():
                if Season.objects.filter(league=league, name=add_season_form.cleaned_data['name']).exists():
                    messages.error(request, "Season with this name in this league exists already")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                season = add_season_form.save()
                season.league = league
                season.created_by = request.user
                season.save()
                for team in league_teams:
                    RPI.objects.create(team=team,season=season,rpi=-1)
                messages.success(request, f"Season {season} created successfully")
        
    else:
        add_team_form = AddTeamForm()
        add_season_form = AddSeasonForm()

    context = {
        "league" : league,
        "league_seasons" : league_seasons,
        "league_teams" : league_teams,
        "add_team_form" : add_team_form,
        "add_season_form" : add_season_form
    }

    return render(request, "rpiapp/detail_templates/league_details.html", context)

def team_details(request, league_id, team_id):

    team = get_object_or_404(Team, id=team_id)
    team_games = team.home_games.all() | team.away_games.all()
    team_games = team_games.order_by("-season__start_date")

    team_games_by_season = {}
    for game in team_games:
        if game.season not in team_games_by_season:
            team_games_by_season[game.season] = {"games":[],
                                                 "wins":0,
                                                 "losses":0,
                                                 "rpi":format(get_object_or_404(RPI, team=team, season=game.season).rpi, '.3f')}
        team_games_by_season[game.season]['games'].append(game)
        if game.winner == team:
            team_games_by_season[game.season]['wins'] += 1
        if game.loser == team:
            team_games_by_season[game.season]['losses'] += 1

    context = {
        "team" : team,
        "team_games_by_season" : team_games_by_season,
    }

    return render(request, "rpiapp/detail_templates/team_details.html", context)

def season_details(request, league_id, season_id):

    league = get_object_or_404(League, id=league_id)
    season = get_object_or_404(Season, id=season_id)
    season_games = season.season_games.all().order_by("-date")
    league_teams = league.teams.all()

    season_teams, _ = get_season_params(season_games)

    season_games_by_date = {}
    # Populate season_games_by_date
    for game in season_games:
        if game.date not in season_games_by_date:
            season_games_by_date[game.date] = [game]
        else:
            season_games_by_date[game.date].append(game)

    rpis = []
    for team in set(season_teams):
        rpi = RPI.objects.get(team=team, season=season)
        rpis.append(format(rpi.rpi, '.3f'))
    
    rpis_by_team = list(zip(rpis,season_teams))
    rpis_by_team = reversed(sorted(rpis_by_team, key=lambda x: x[0]))

    if request.method == 'POST':
        add_game_form = AddGameForm(request.POST, season=season)
        if add_game_form.is_valid():
            date = add_game_form.cleaned_data['date']
            if date < season.start_date or date > season.end_date:
                messages.error(request, f"Game outside of date range ({season.start_date})-({season.end_date})")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            game = add_game_form.save(commit=False)
            game.created_by = request.user
            game.league = league
            game.season = season
            game.bulk_processing = False
            game.save()
            
            messages.success(request, f"Game: '{game}' created successfully")
            return HttpResponseRedirect(reverse("rpiapp:season_details", kwargs={"league_id" : league_id,
                                                                                 "season_id" : season_id}))
    else:
        add_game_form = AddGameForm(season=season)

    context = {
        "season" : season,
        "season_games_by_date" : season_games_by_date,
        "league_teams" : league_teams,        
        "rpis_by_team" : rpis_by_team,
        "add_game_form" : add_game_form
    }

    return render(request, "rpiapp/detail_templates/season_details.html", context)

def game_details(request, league_id, season_id, game_id):

    game = get_object_or_404(Game, id=game_id)
    context = {
        "game" : game
    }

    return render(request, "rpiapp/detail_templates/game_details.html", context)
            

rpisite/rpiapp/templates/rpiapp/detail_templates/game_details.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{{game.date}}: {{game.home_team}} vs. {{game.away_team}}{% endblock %}
</head>
{% block content %}
<body>
    <section>
        <h1> Game Details </h1>
        {% if user == game.created_by %}
        <form style="display:inline;" action="{% url 'rpiapp:edit_game' game.league.id game.season.id game.id%}">
            {% csrf_token %}
            <button type="submit">Edit</button>
        </form>
        {% endif %}
        <p><a href="{% url 'rpiapp:season_details' game.league.id game.season.id %}" > Game Season: {{game.season}}</a></p>
        <p><a href="{% url 'rpiapp:league_details' game.league.id %}" > Game League: {{game.league}}</a></p>
        <p>Game Date: {{game.date}}</p>
        <p>Game Winner: <a href="{% url 'rpiapp:team_details' game.winner.league.id game.winner.id %}" > {{game.winner}}</a></p>
        <p>Game Loser: <a href="{% url 'rpiapp:team_details' game.loser.league.id game.loser.id %}" > {{game.loser}}</a></p>
        <p>Home Team: <a href="{% url 'rpiapp:team_details' game.home_team.league.id game.home_team.id %}" > {{game.home_team}}</a></p>
        <p>Away Team: <a href="{% url 'rpiapp:team_details' game.away_team.league.id game.away_team.id %}" > {{game.away_team}}</a></p>
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/detail_templates/index.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}Home{% endblock %}
</head>
{% block content %}
<body>
    <section>
        <h2> Search for League: </h2>
        <form action="{% url 'rpiapp:league_search' %}" method="post">
            {% csrf_token %}
            <input type="search" placeholder="League name" name="league_search_term">
            <button type="submit">Search for League</button>
        </form>
        <h2> Search for User: </h2>
        <form action="{% url 'rpiapp:user_search' %}" method="post">
            {% csrf_token %}
            <input type="search" placeholder="User name" name="user_search_term">
            <button type="submit">Search for User</button>
        </form>
    </section>
    {% if user.is_authenticated %}
    <section>
            <h2> Add League: </h2>
            <form method="post">
                {% csrf_token %}
                {{add_league_form.name}}
                <button type="submit">Add League</button>
            </form>
    </section>
    {% endif %}
    <section>
        <h2> Pro Leagues </h2>
        <ul>
            {% for league in pro_leagues %}
            <li><a href="{% url 'rpiapp:league_details' league.id %}">{{league}}</a></li>
            {% endfor %}
        </ul>
        <h2> Collegiate Leagues </h2>
        <ul>
            {% for league in college_leagues %}
            <li><a href="{% url 'rpiapp:league_details' league.id %}">{{league}}</a></li>
            {% endfor %}
        </ul>
    </section>
    <section>
        <h2> Latest games: </h2>
        {% if latest_games %}
        <ul>
            {% for game in latest_games %}
            <li><a href="{% url 'rpiapp:game_details' game.league.id game.season.id game.id %}">{{game}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No recent games... </p>
        {% endif %}
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/detail_templates/league_details.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{{league}}{% endblock %}
</head>
{% block content %}
<body>
    <section>
        <h1> {{league}} </h1>
        {% if user == league.created_by %}
        <form style="display:inline;" action="{% url 'rpiapp:edit_league' league.id %}">
            {% csrf_token %}
            <button type="submit">Edit</button>
        </form>
        {% endif %}
    </section>
    <section>
        <h2> Team Search: </h2>
        <form action="{% url 'rpiapp:team_search' league.id %}" method="post">
            {% csrf_token %}
            <input type="search" placeholder="Team name" name="search_term">
            <button type="submit">Search for team</button>
        </form>
        <h2> Add Team: </h2>
        <form method="post">
            {% csrf_token %}
            <span style="display:inline;">
                {{add_team_form.name}}
                <button type="submit" name="add_team">Add Team</button>
            </span>
        </form>
    </section>
    {% if user == league.created_by or user.superuser %}
    <section>
        <h2> Add Season: </h2>
        <form method="post">
            {% csrf_token %}
                <table>
                    {{add_season_form.as_table}}
                </table>
                <button type="submit" name="add_season">Add Season</button>
        </form>
    </section>
    {% else %}
    {% endif %}
    <section>
        <h2><u>Seasons</u>:</h2>
        {% if league_seasons %}
            <ul>
                {% for season in league_seasons %}
                    <li>
                        {% if user == league.created_by or user.is_superuser %}
                        <form action="{% url 'rpiapp:edit_season' league.id season.id %}">
                            {% csrf_token %}
                            <button type="submit">Edit</button>
                        </form>
                        <form action="{% url 'rpiapp:delete_season' season.league.id season.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Delete</button>
                        </form>
                        {% else %}
                        {% endif %}
                        <a href="{% url 'rpiapp:season_details' season.league.id season.id %}" > {{season.name}} Season</a><p style="display:inline;"> ({{season.start_date}} - {{season.end_date}}) </p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p> No seasons in database... </p>
        {% endif %}
    </section>
    <section>
        <h2><u>Teams</u>:</h2>
        {% if league_teams %}
            <ul>
                {% for team in league_teams %}
                    <li>
                        {% if user == league.created_by or user.is_superuser %}
                        <form action="{% url 'rpiapp:edit_team' league.id team.id %}">
                            {% csrf_token %}
                            <button type="submit">Edit</button>
                        </form>
                        <form action="{% url 'rpiapp:delete_team' team.league.id team.id %}" method="post">
                            {% csrf_token %}
                                <button type="submit">Delete</button>
                        </form>
                        {% else %}
                        {% endif %}
                        <a href="{% url 'rpiapp:team_details' team.league.id team.id %}" > {{team.name}}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p> No teams in league... </p>
        {% endif %}
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/detail_templates/season_details.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{{season.league}}'s {{season.name}} Season{% endblock %}
</head>
{% block content %}
<body>
    <section>
        <h1><a href="{% url 'rpiapp:league_details' season.league.id %}" > {{season.league}}</a>'s {{season.name}} Season </h1>

        {% if user == season.league.created_by or user.is_superuser %}
        <form style="display:inline;" action="{% url 'rpiapp:edit_season' season.league.id season.id %}">
            {% csrf_token %}
            <button type="submit">Edit</button>
        </form>
        <br>
        <br>
        <form method="post">
            {% csrf_token %}
            <table>{{ add_game_form.as_table }}</table>
            <br>
            <button type="submit">Add Game</button>
            <a href="{% url 'rpiapp:bulk_game_upload' season.league.id season.id %}">Or upload games in bulk</a>
        </form>
        {% else %}
        {% endif %}
    </section>
    <section>
        <h2> Standings: </h2>
        <ol>
            {% for rpi,team in rpis_by_team %}
                <li>{{team}}'s RPI: {{rpi}}</li>
            {% endfor %}
        </ol>
    </section>
    <section>
        <form action="{% url 'rpiapp:game_search' season.league.id season.id %}" method="post">
            {% csrf_token %}
            <input type="date" name="date" min="{{season.start_date}}" max="{{season.end_date}}">
            <button type="submit">Search for games on date</button>
        </form>
        <h2> Games: </h2>
        <ul>
            {% for date, games in season_games_by_date.items %}
            <li>{{date}}</li>
            <ul>
                {% for game in games %}
                    <li><a href="{% url 'rpiapp:game_details' game.league.id game.season.id game.id %}">{{game}}</a></li>
                    {% if user == game.league.created_by or user.is_superuser %}
                    <form action="{% url 'rpiapp:edit_game' game.league.id game.season.id game.id %}">
                        <button type="submit">Edit</button>
                    </form>
                    <form action="{% url 'rpiapp:delete_game' game.league.id game.season.id game.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Delete</button>
                    </form>
                    {% else %}
                    {% endif %}
                {% endfor %}
            </ul>
            {% endfor %}
        </ul>
    </section>

</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/detail_templates/team_details.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{{team.name}}{% endblock %}
</head>
{% block content %}
<body>
    <section>
        <h1>{{team.name}}'s Games: </h1>
        {% if team_games_by_season %}
            <ul>
                {% for season,record in team_games_by_season.items %}
                <li>{{season}} Games (Record: {{record.wins}}-{{record.losses}} RPI: {{record.rpi}})</li>
                <ul>
                    {% for game in record.games %}
                        <li><a href="{% url 'rpiapp:game_details' game.league.id game.season.id game.id %}" > {{game}} </a></li>
                    {% endfor %}
                </ul>
                {% endfor %}
            </ul>
        {% else %}
            <p> No games played... </p>
        {% endif %}
    </section>  
</body>
{% endblock %}
</html>