rpisite/rpiapp/urls.py
from django.urls import path
from .views import delete_views, detail_views, edit_views, misc_views, search_views, user_views

app_name = "rpiapp"
urlpatterns = [

    # User URLs
    path("register/", user_views.register_user, name="register_user"),
    path("login/", user_views.login_user, name="login_user"),
    path("logout/", user_views.logout_user, name="logout_user"),
    path("users/<int:user_id>/", user_views.user_profile, name="user_profile"),
    path("users/<int:user_id>/edit/", user_views.edit_profile, name="edit_profile"),
    path("users/<int:user_id>/delete", user_views.delete_profile, name="delete_profile"),

    # Search URLs
    path("users/search/", search_views.user_search, name="user_search"),
    path("leagues/search/", search_views.league_search, name="league_search"),
    path("leagues/<int:league_id>/teams/search/", search_views.team_search, name="team_search"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/search/", search_views.game_search, name="game_search"),
    
    # Index URL
    path("", detail_views.index, name="index"),

    # Detail URLs
    path("leagues/<int:league_id>/", detail_views.league_details, name="league_details"),
    path("leagues/<int:league_id>/teams/<int:team_id>/", detail_views.team_details, name="team_details"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/", detail_views.season_details, name="season_details"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/", detail_views.game_details, name="game_details"),

    # Edit URLs
    path("leagues/<int:league_id>/edit/", edit_views.edit_league, name="edit_league"),
    path("leagues/<int:league_id>/teams/<int:team_id>/edit/", edit_views.edit_team, name="edit_team"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/edit/", edit_views.edit_season, name="edit_season"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/edit/", edit_views.edit_game, name="edit_game"),

    # Delete URLs
    path("leagues/<int:league_id>/delete/", delete_views.delete_league, name="delete_league"),
    path("leagues/<int:league_id>/teams/<int:team_id>/delete/", delete_views.delete_team, name="delete_team"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/delete/", delete_views.delete_season, name="delete_season"),
    path("leagues/<int:league_id>/seasons/<int:season_id>/games/<int:game_id>/delete/", delete_views.delete_game, name="delete_game"),

    # Add Games through File
    path("leagues/<int:league_id>/seasons/<int:season_id>/addgames/", misc_views.bulk_game_upload, name="bulk_game_upload")
]

rpisite/rpisite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [

    path("", RedirectView.as_view(url='/rpiapp/')),
    path('admin/', admin.site.urls),
    path('rpiapp/', include('rpiapp.urls'))

]

rpisite/rpiapp/forms/edit_forms.py
from django import forms
from ..models import League, Team, Season, Game

class EditLeagueForm(forms.ModelForm):
    class Meta:
        model = League
        exclude = ('created_by',)

class EditTeamForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ('created_by', 'league',)

class EditSeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        exclude = ('created_by', 'league',)

class EditGameForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = ('date','winner','loser','home_team','away_team')
    
    def __init__(self, *args, **kwargs):
        instance = kwargs['instance']
        super(EditGameForm, self).__init__(*args, **kwargs)
        self.fields['date'] = forms.DateField(widget=forms.widgets.SelectDateWidget(years=range(instance.season.start_date.year, instance.season.end_date.year+1)))
        self.fields['winner'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['loser'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['home_team'].queryset = instance.season.league.teams.all().order_by("name")
        self.fields['away_team'].queryset = instance.season.league.teams.all().order_by("name")

rpisite/rpiapp/forms/user_forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email')

rpisite/rpiapp/views/bulk_upload_view.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..models import Team, Season, Game
from ..utils.bulk_rpi import bulk_create_games
import csv
import datetime

@login_required
def bulk_game_upload(request, league_id, season_id):

    season = get_object_or_404(Season, id=season_id)
    league = season.league

    if request.method == 'POST':
        games_csv = request.FILES.get('games_csv')
        decoded_games_csv = games_csv.read().decode('utf-8').splitlines()
        games_csv_reader = csv.reader(decoded_games_csv, delimiter=",")
        next(games_csv_reader)
        games = []
        for row in games_csv_reader:
            date = datetime.datetime.strptime(row[0], '%m/%d/%Y').date()
            if date < season.start_date or date > season.end_date:
                messages.error(request, f"Contains game outside of date range ({season.start_date})-({season.end_date})")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            home_team, ht_created = Team.objects.get_or_create(name=row[3], league=league, created_by=request.user)
            away_team, at_created = Team.objects.get_or_create(name=row[4], league=league, created_by=request.user)
            winner, w_created = Team.objects.get_or_create(name=row[1], league=league, created_by=request.user)
            loser, l_created = Team.objects.get_or_create(name=row[2], league=league, created_by=request.user)
            created_by = request.user
            game = Game(
                created_by = created_by,
                date = date,
                home_team = home_team,
                away_team=away_team,
                winner=winner,
                loser=loser,
                season=season,
                league=league,
                bulk_processing=True
            )
            games.append(game)
            if w_created:
                messages.success(request, f"Team '{winner}' created")
            if l_created:
                messages.success(request, f"Team '{loser}' created")
            if ht_created:
                messages.success(request, f"Team '{home_team}' created")
            if at_created:
                messages.success(request, f"Team '{away_team}' created")
        bulk_create_games(season, games, True)
        messages.success(request, "Games imported successfully")
        return HttpResponseRedirect(reverse('rpiapp:season_details', kwargs={"league_id":league.id,
                                                                             "season_id":season.id}))
    
    context = {
        "season" : season
    }
    return render(request, "rpiapp/add_games_bulk.html", context)

rpisite/rpiapp/views/delete_views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from ..models import League, Team, Season, Game
from ..utils.bulk_rpi import bulk_calculate_rpis, toggle_bulk_processing

@login_required
def delete_league(request, league_id):
    
    if request.method == 'POST':
        league = get_object_or_404(League, id=league_id)
        if request.user == league.created_by or request.user.is_superuser:
            league.delete()
            messages.success(request, f"League '{league}' deleted successfully")
        else:
            messages.error(request, "You cannot delete this league as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_team(request, league_id, team_id):

    if request.method == 'POST':
        league = get_object_or_404(League, id=league_id)
        team = get_object_or_404(Team, id=team_id)
        if request.user == team.created_by or request.user.is_superuser:
            league_games = league.league_games.all()
            league_seasons = league.seasons.all()
            toggle_bulk_processing(league_games, True)            
            team.delete()
            for season in league_seasons:
                bulk_calculate_rpis(season, season.season_games.all())
            toggle_bulk_processing(league_games, False) 
            messages.success(request, f"Team '{team}' deleted successfully")
        else:
            messages.error(request, "You cannot delete this team as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_season(request, league_id, season_id):

    if request.method == 'POST':
        season = get_object_or_404(Season, id=season_id)
        if request.user == season.created_by or request.user.is_superuser:
            season.delete()
            messages.success(request, f"Season deleted successfully: {season.name}")
        else:
            messages.error(request, "You cannot delete this season as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def delete_game(request, league_id, season_id, game_id):

    if request.method == 'POST':
        game = get_object_or_404(Game, id=game_id)

        if request.user == game.created_by or request.user.is_superuser:
            game.delete()
            messages.success(request, f"Game between {game.home_team} and {game.away_team} on {game.date} deleted successfully")
        else:
            messages.error(request, "You cannot delete this game as you do not own it")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

rpisite/rpiapp/views/detail_views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from ..forms.add_forms import AddLeagueForm, AddTeamForm, AddSeasonForm, AddGameForm
from ..models import League, Team, Season, Game, RPI
from django.contrib.auth.models import User
from ..utils.rpi import get_season_params

def index(request):

    # Show the most recent 5 games
    latest_games = Game.objects.all().order_by("-date")[:5]

    superuser = User.objects.filter(is_superuser=True)[0]

    pro_leagues_list = ["National Football League", "National Basketball Association", "Major League Baseball", "National Hockey League"]
    pro_leagues = League.objects.filter(name__in=pro_leagues_list, created_by=superuser).order_by("name")

    college_leagues_list = ["NCAA Men's Hockey","NCAA Women's Hockey","NCAA Men's Basketball","NCAA Women's Basketball","NCAA Baseball","NCAA Football",]
    college_leagues = League.objects.filter(name__in=college_leagues_list, created_by=superuser)

    if request.method == 'POST':
        add_league_form = AddLeagueForm(request.POST)
        if add_league_form.is_valid():
            league = add_league_form.save()
            league.created_by = request.user
            league.save()
            messages.success(request, f"League '{league}' created successfully")
            return HttpResponseRedirect(reverse("rpiapp:league_details", args=[league.id]))
    else:
        add_league_form = AddLeagueForm()

    context = {
        "add_league_form" : add_league_form,
        "latest_games" : latest_games,
        "pro_leagues" : pro_leagues,
        "college_leagues" : college_leagues
    }

    return render(request, "rpiapp/detail_templates/index.html", context)

def league_details(request, league_id):

    league = get_object_or_404(League, id=league_id)
    league_seasons = league.seasons.all().order_by("-start_date")
    league_teams = league.teams.all().order_by("name")
    add_team_form = AddTeamForm()
    add_season_form = AddSeasonForm()

    if request.method == 'POST':
        if 'add_team' in request.POST:
            add_team_form = AddTeamForm(request.POST)
            if add_team_form.is_valid():
                if Team.objects.filter(league=league, name=add_team_form.cleaned_data['name']).exists():
                    messages.error(request, "Team with this name in this league exists already")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                team = add_team_form.save()
                team.league = league
                team.created_by = request.user
                team.save()
                messages.success(request, f"Team {team} created successfully")
        if 'add_season' in request.POST:
            add_season_form = AddSeasonForm(request.POST)
            if add_season_form.is_valid():
                if Season.objects.filter(league=league, name=add_season_form.cleaned_data['name']).exists():
                    messages.error(request, "Season with this name in this league exists already")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                season = add_season_form.save()
                season.league = league
                season.created_by = request.user
                season.save()
                for team in league_teams:
                    RPI.objects.create(team=team,season=season,rpi=-1)
                messages.success(request, f"Season {season} created successfully")
        
    else:
        add_team_form = AddTeamForm()
        add_season_form = AddSeasonForm()

    context = {
        "league" : league,
        "league_seasons" : league_seasons,
        "league_teams" : league_teams,
        "add_team_form" : add_team_form,
        "add_season_form" : add_season_form
    }

    return render(request, "rpiapp/detail_templates/league_details.html", context)

def team_details(request, league_id, team_id):

    team = get_object_or_404(Team, id=team_id)
    team_games = team.home_games.all() | team.away_games.all()
    team_games = team_games.order_by("-season__start_date")

    team_games_by_season = {}
    for game in team_games:
        if game.season not in team_games_by_season:
            team_games_by_season[game.season] = {"games":[],
                                                 "wins":0,
                                                 "losses":0,
                                                 "rpi":format(get_object_or_404(RPI, team=team, season=game.season).rpi, '.3f')}
        team_games_by_season[game.season]['games'].append(game)
        if game.winner == team:
            team_games_by_season[game.season]['wins'] += 1
        if game.loser == team:
            team_games_by_season[game.season]['losses'] += 1

    context = {
        "team" : team,
        "team_games_by_season" : team_games_by_season,
    }

    return render(request, "rpiapp/detail_templates/team_details.html", context)

def season_details(request, league_id, season_id):

    league = get_object_or_404(League, id=league_id)
    season = get_object_or_404(Season, id=season_id)
    season_games = season.season_games.all().order_by("-date")
    league_teams = league.teams.all()

    season_teams, _ = get_season_params(season_games)

    season_games_by_date = {}
    # Populate season_games_by_date
    for game in season_games:
        if game.date not in season_games_by_date:
            season_games_by_date[game.date] = [game]
        else:
            season_games_by_date[game.date].append(game)

    rpis = []
    for team in set(season_teams):
        rpi = RPI.objects.get(team=team, season=season)
        rpis.append(format(rpi.rpi, '.3f'))
    
    rpis_by_team = list(zip(rpis,season_teams))
    rpis_by_team = reversed(sorted(rpis_by_team, key=lambda x: x[0]))

    if request.method == 'POST':
        add_game_form = AddGameForm(request.POST, season=season)
        if add_game_form.is_valid():
            date = add_game_form.cleaned_data['date']
            if date < season.start_date or date > season.end_date:
                messages.error(request, f"Game outside of date range ({season.start_date})-({season.end_date})")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            game = add_game_form.save(commit=False)
            game.created_by = request.user
            game.league = league
            game.season = season
            game.bulk_processing = False
            game.save()
            
            messages.success(request, f"Game: '{game}' created successfully")
            return HttpResponseRedirect(reverse("rpiapp:season_details", kwargs={"league_id" : league_id,
                                                                                 "season_id" : season_id}))
    else:
        add_game_form = AddGameForm(season=season)

    context = {
        "season" : season,
        "season_games_by_date" : season_games_by_date,
        "league_teams" : league_teams,        
        "rpis_by_team" : rpis_by_team,
        "add_game_form" : add_game_form
    }

    return render(request, "rpiapp/detail_templates/season_details.html", context)

def game_details(request, league_id, season_id, game_id):

    game = get_object_or_404(Game, id=game_id)
    context = {
        "game" : game
    }

    return render(request, "rpiapp/detail_templates/game_details.html", context)
            

rpisite/rpiapp/templates/rpiapp/add_league.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'rpiapp:add_league' %}" method="post">
        {% csrf_token %}
        <input type="text" name="league_name">
        <input type="submit" value="Add League">
    </form>
</body>
</html>

rpisite/rpiapp/templates/rpiapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'rpiapp/base.css' %}">
    <link rel="stylesheet" href="{% static 'rpiapp/main.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'rpiapp/rpi.png' %}">
    <title>{% block title %}{% endblock%}</title>
</head>
<body>
    <header>
            <a href="{% url 'rpiapp:index' %}"> Home </a>
            <a href="https://github.com/shaneking-code" target="_blank"> Github </a>
            {% if user.is_authenticated %}
            <a href="{% url 'rpiapp:user_profile' user.id %}">{{user.username}}</a>
            <a href="{% url 'rpiapp:logout_user' %}"> Logout </a>
            {% elif request.path != "/rpiapp/login/" %}
            <a href="{% url 'rpiapp:login_user' %}">Login</a><span> or </span><a href="{% url 'rpiapp:register_user' %}">Create account</a>
            {% else %}
            {% endif %}
    </header>
    <div class="messages">
        {% for message in messages %}
            <p class="{{message.tags}}">{{message}}</p>
        {% endfor %}
    </div>
    {% if request.path != "/rpiapp/" and user.is_authenticated %}
    <section>
        <h2 style="text-align: center;"> Warning </h2>
        <p style="text-align: center;"> Adding a season with >500 games will cause the site to stall. </p>
        <p style="text-align: center;"> Adding and deleting seasons, games, and teams to large leagues will take a while. Do not leave the page. </p>
    </section>
    {% endif %}
    {% block content %}{% endblock %}
    <footer>
        Created by Shane K - <script>document.write(new Date().getFullYear())</script>
    </footer>
</body>
</html>

rpisite/rpiapp/templates/rpiapp/game_search.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    <section>
        <h1> Search results for {{search_date}}</h1>
        {% if search_results %}
        <ul>
            {% for game in search_results %}
                <li><a href="{% url 'rpiapp:game_details' game.league.id game.season.id game.id %}"> {{game}} </a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No games on this date... </p>
        {% endif %}
    </section>
    <section>
        <a href="{{referer}}">Back</a>
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/league_search.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    <section>
        <h1> Search results for : "{{search_term}}"</h1>
        {% if search_results %}
        <ul>
            {% for league in search_results %}
                {% if league.created_by.is_superuser %}
                    <li><a href="{% url 'rpiapp:league_details' league.id %}"> {{league.name}} </a></li>
                {% else %}
                    <li><a href="{% url 'rpiapp:league_details' league.id %}"> {{league.name}}</a> (created by: <a href="{% url 'rpiapp:user_profile' league.created_by.id %}">{{league.created_by.username}}</a>)</li>
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
        <p> No leagues with name containing: "{{search_term}}" </p>
        {% endif %}
    </section>
    <section>
        <a href="{{referer}}">Back</a>
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'rpiapp:index' %}"> Home </a></li>
            <li><a href="https://github.com/shaneking-code" target="_blank"> Github </a></li>
        </ul>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

rpisite/rpiapp/templates/rpiapp/season_results.html
{% extends 'rpiapp/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    {% for message in messages %}
    <p> {{message}} </p>
    {% endfor %}

    <form action="{% url 'rpiapp:game_search' season.league.id season.id %}" method="post">
        {% csrf_token %}
        <input type="date" name="date" min="{{season.year}}-01-01" max="{{season.year}}-12-31">
        <input type="submit" value="Search for games on date">
    </form>

    <h1><a href="{% url 'rpiapp:league_details' season.league.id %}" > {{season.league}}</a></h1>
    <h1> {{season.year}} </h1>

    <form action="{% url 'rpiapp:add_game' season.league.id season.id %}" method="post">
        {% csrf_token %}
        <input type="date" name="date" min="{{season.year}}-01-01" max="{{season.year}}-12-31">
        <datalist id="teams">
            {% for team in league_teams %}
                <option value="{{team.name}}">{{team.name}}</option>
            {% endfor %}
        </datalist>
        <input type="search" list="teams" placeholder="Winner" name="winner">
        <input type="search" list="teams" placeholder="Loser" name="loser">
        <input type="search" list="teams" placeholder="Home Team" name="home_team">
        <input type="search" list="teams" placeholder="Away Team" name="away_team">
        <input type="submit" value="Add Game">
    </form>

    <h2> Standings: </h2>
    <ol>
        {% for rpi,team in rpis_by_team %}
            <li>{{team}}'s RPI: {{rpi}}</li>
        {% endfor %}
    </ol>
    
    <h2> Games: </h2>
    <ul>
        {% for date, games in season_games_by_date.items %}
        <li>{{date}}</li>
        <ul>
            {% for game in games %}
                <li><a href="{% url 'rpiapp:game_details' game.league.id game.season.id game.id %}">{{game}}</a></li>
                <form action="{% url 'rpiapp:delete_game' game.league.id game.season.id game.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X">
                </form>
            {% endfor %}
        </ul>
        {% endfor %}
    </ul>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/team_search.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    <section>
        <h1> Search results for : "{{search_term}}"</h1>
        {% if search_results %}
        <ul>
            {% for team in search_results %}
                <li><a href="{% url 'rpiapp:team_details' team.league.id team.id %}"> {{team.name}} </a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No teams in "{{league}}" with name containing: "{{search_term}}"</p>
        {% endif %}
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/user_profile.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}{{view_user.username}}{% endblock %}
</head>
{% block content %}
<body>
    <section>
        {% if view_user.is_superuser %}
        <h1 style="color: #58B457;"> **Admin** </h1>
        {% endif %}
        {% if not view_user.is_active %}
        <h1 style="color:red;">**User is inactive**</h1>
        {% endif %}
        <h2>Username:</h2><p> {{view_user.username}}</p>
        <h2>Email: </h2><p>{{view_user.email}}</p>
        {% if user == view_user %}
            <h2><a style="text-decoration: none;" href="{% url 'rpiapp:edit_profile' user.id %}">Edit Profile</a></h2>
            <h2><a id="deleteprofile" style="text-decoration: none;" href="{% url 'rpiapp:delete_profile' user.id %}">Delete Profile</a></h2>
        {% endif %}
    </section>
    <section>
        <h2>{{view_user.username}}'s leagues and teams: </h2>
        <ul>
            {% for league in  leagues %}
            <span class="uprofile-span">League:</span>
            <br>
            <li>
                {% if user == view_user %}
                <form action="{% url 'rpiapp:edit_league' league.id %}">
                    {% csrf_token %}
                    <button type="submit">Edit</button>
                </form>
                <form style="display:inline;" action="{% url 'rpiapp:delete_league' league.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
                {% endif %}
                <a href="{% url 'rpiapp:league_details' league.id %}">{{league}}</a>
            </li>
            {% if teams %}
            <span class="uprofile-span">Teams:</span>
            <br>
            <ul>
                {% for team in teams %}
                    {% if team.league == league %}
                    <li>
                        {% if user == view_user %}
                        <form action="{% url 'rpiapp:edit_team' league.id team.id %}">
                            {% csrf_token %}
                            <button type="submit">Edit</button>
                        </form>
                        <form style="display:inline;" action="{% url 'rpiapp:delete_team' league.id team.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Delete</button>
                        </form>
                        {% endif %}
                        <a href="{% url 'rpiapp:team_details' league.id team.id %}">{{team}}</a>
                    </li>
                    {% else %}
                    {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
            {% endfor %}
        </ul>
    </section>
</body>
{% endblock %}
</html>

rpisite/rpiapp/templates/rpiapp/user_search.html
{% extends 'rpiapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
{% block content %}
<body>
    <section>
        <h1> Search results for : "{{search_term}}"</h1>
        {% if search_results %}
        <ul>
            {% for search_user in search_results %}
                <li><a href="{% url 'rpiapp:user_profile' search_user.id %}">{{search_user.username}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p> No users with name containing: "{{search_term}}" </p>
        {% endif %}
    </section>
    <section>
        <a href="{{referer}}">Back</a>
    </section>
</body>
{% endblock %}
</html>